# Generated by Django 4.2.23 on 2025-08-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PropertyInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "lot_size_acres",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("user_context", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_description", models.TextField()),
                (
                    "estimated_net_cash_flow",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_revenue",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("raw_response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates",
                        to="estimates.propertyinquiry",
                    ),
                ),
            ],
        ),
    ]
