version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: propertydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      -  ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: